version: "3"

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:12
    container_name: laboratory-kong-database
    restart: always
    environment:
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    networks:
      kevin-network:

  #######################################
  # Postgres: The database used by Konga
  #######################################
  konga-database:
    image: postgres:11
    container_name: laboratory-konga-database
    restart: always
    environment:
      POSTGRES_PASSWORD: konga
      POSTGRES_USER: konga
      POSTGRES_DB: konga
    networks:
      kevin-network:

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:latest
    container_name: laboratory-konga-prepare
    command: "-c prepare -a postgres -u postgresql://konga:konga@konga-database:5432/konga"
    restart: on-failure
    depends_on:
      - konga-database
    networks:
      kevin-network:

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    container_name: laboratory-konga
    restart: always
    environment:
      NODE_ENV: development
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_USER: konga
      DB_PASSWORD: konga
      DB_DATABASE: konga
    depends_on:
      - konga-database
      - konga-prepare
    ports:
      - "1337:1337"
    networks:
      kevin-network:

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:2.8
    container_name: laboratory-kong-migration
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: kong
    links:
      - kong-database
    depends_on:
      - kong-database
    networks:
      kevin-network:

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:2.8
    container_name: laboratory-kong
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
    networks:
      kevin-network:

networks:
  kevin-network: